name: 'Validate'
on:
  push:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: curium-rocks/flows/.github/workflows/node-ts.yml@main
      with:
        SONARQUBE_KEY: ${{ secrets.SONARQUBE_KEY }}
